export enum Icon {
  COLEGEND = 'co-colegend', // 'infinite',
  PROFILE = 'finger-print',
  // apps
  HOME = 'home',
  ARCADE = 'game-controller-a',
  OFFICE = 'briefcase',
  COMMUNITY = 'bonfire',
  STUDIO = 'microphone',
  ACADEMY = 'co-academy', // 'school',
  JOURNEY = 'co-journey', // 'compass',
  // HOME
  DASHBOARD = 'navigate',
  HABITS = 'repeat',
  STATS = 'stats',
  TOOLS = 'hammer',
  // ARCADE
  ADVENTURES = 'pulse',
  GAMES = 'game-controller-b',
  CONTESTS = 'trophy',
  SHOP = 'cart',
  // OFFICE
  AGENDA = 'clipboard',
  OUTCOMES = 'checkbox-outline',
  ACHIEVEMENTS = 'medal',
  // COMMUNITY
  DUO = 'co-duo', // 'person',
  CLAN = 'co-clan', // 'contacts',
  TRIBE = 'co-tribe', // 'people',
  MENTOR = 'co-wizard', // 'man',
  // STUDIO
  JOURNAL = 'co-journal', // 'book',
  INTERVIEW = 'text',
  STORY = 'co-story', // 'brush',
  // ACADEMY
  BOOK_CLUB = 'co-book-club', // 'bookmark',
  COURSES = 'ribbon',
  RESOURCES = 'co-resources', // 'bookmarks',
  // JOURNEY
  QUESTS = 'co-quest', // 'map',
  HERO = 'co-hero', // 'happy',
  DEMON = 'co-demon', // 'sad',
  // life areas
  AREA1 = 'co-apple', // 'nutrition',
  AREA2 = 'co-smiley',
  AREA3 = 'sunny',
  AREA4 = 'heart',
  AREA5 = 'megaphone',
  AREA6 = 'bulb',
  AREA7 = 'moon',
  // project
  NEWS = 'paper',
  EVENTS = 'calendar',
  SUPPORT = 'help-circle',
  SETTINGS = 'settings',
  BACKSTAGE = 'nuclear',
  FEEDBACK = 'paper-plane',
  // general
  SCOPE = 'aperture',
  SCHEDULE = 'time',
  DEADLINE = 'alarm',
  TAG = 'pricetag',
  TAGS = 'pricetags',
  CONTENT = 'text',
  STAR = 'star',
  STAR_EMPTY = 'star-outline',
  SELECT = 'checkmark',
  STREAK = 'flame',
  GEM = 'co-gem',
  PREMIUM = 'co-premium',
  BUY = 'cart',
  // UI
  MENU = 'menu',
  REFRESH = 'refresh',
  MORE = 'more',
  CREATE = 'add',
  EDIT = 'create',
  SAVE = 'checkmark',
  REMOVE = 'close-circle',
  DELETE = 'trash',
  CLOSE = 'close',
  SEARCH = 'search',
  EXPAND = 'expand',
  CONTRACT = 'contract',
  LOCKED = 'lock',
  // Media
  MUSIC = 'musical-note',
  PLAY = 'play',
  PAUSE = 'pause',
  MUTE = 'volume-off',
  UNMUTE = 'volume-up',
  // office
  STEPS = 'co-steps', // 'checkbox-outline',
  STEP_OPEN = 'square-outline',
  STEP_CLOSED = 'checkbox',
  INBOX = 'filing',
  FOCUS = 'locate',
  // statuses
  STATUS_FUTURE = 'cloud-circle',
  STATUS_WAITING = 'time',
  STATUS_CURRENT = 'checkmark-circle-outline',
  STATUS_DONE = 'checkmark-circle',
  STATUS_CANCELED = 'remove-circle',
  // community
  VIRTUAL_ROOM = 'videocam'
}
